[package]
name = "lymap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "1.1.3"
macroquad = "0.4.4"
serde = { version = "1.0.159" , features = ["derive"] }
serde_json = "1.0.111"
